spring.application.name=app

spring.datasource.url=jdbc:postgresql://dpg-d462o0v5r7bs73atgif0-a.singapore-postgres.render.com:5432/ilelms
spring.datasource.username=ilepva
spring.datasource.password=4Bk9irWXO48QpcrP7QpsSI5EFrnpxFH0
